### ISSUE TITLE
Could not find imported module support code for 'Ansible.ModuleUtils.Legacy'

### ISSUE THREAD

**Issue by mwinfie** [mwinfie/ansible-modules#1]
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

```
[vagrant@mgmt roles]$ ansible --version
ansible 2.4.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, May  3 2017, 07:55:04) [GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
```

##### CONFIGURATION

`DEFAULT_ROLES_PATH(/etc/ansible/ansible.cfg) = [u'/etc/ansible/roles', u'/usr/share/ansible/roles']`

##### OS / ENVIRONMENT

Red Hat Enterprise Linux Server release 7.4 (Maipo)

##### SUMMARY

Using the module inside of a playbook like this:

```
- name: Create database(s)
  win_mssql_db:
    name: "{{ item }}"
    state: present
  with_items: "{{ mssql_databases }}"
```

Produces this error:
```
Currently testing this inside of a role
`fatal: [winweb1]: FAILED! => {"failed": true, "msg": "Could not find imported module support code for 'Ansible.ModuleUtils.Legacy\r'."}
```

##### STEPS TO REPRODUCE

Run the below task on a remote Windows machine with SQLPS.

```yaml
- name: Create database(s)
  win_mssql_db:
    name: "{{ item }}"
    state: present
  with_items: "{{ mssql_databases }}"
```

##### EXPECTED RESULTS

'Changed' reported without error.
